import { Platform } from 'react-native';

export const Colors = {
  light: {
    text: '#111827',
    background: '#FFFFFF',
    surface: '#F9FAFB',
    primary: '#004eea',
    secondary: '#7C4DFF',
    tertiary: '#00E5FF',
    onSurface: '#111827',
    onSurfaceVariant: '#4B5563',
    outline: '#6B7280',
    outlineVariant: 'rgba(0, 0, 0, 0.08)',
    surfaceContainerLow: '#F3F4F6',
    surfaceContainer: '#E5E7EB',
    surfaceContainerHigh: '#E5E7EB',
    surfaceContainerHighest: '#D1D5DB',
    surfaceContainerLowest: '#FFFFFF',
    surfaceBright: '#FFFFFF',
    primaryDim: '#3b82f6',
    secondaryDim: '#8b5cf6',
    tertiaryDim: '#06b6d4',
    tint: '#004eea',
    tabIconDefault: '#9CA3AF',
    tabIconSelected: '#004eea',
  },
  dark: {
    text: '#ffffff',
    background: '#0e0e0f',
    surface: '#0e0e0f',
    primary: '#94aaff',
    secondary: '#a68cff',
    tertiary: '#81ecff',
    onSurface: '#ffffff',
    onSurfaceVariant: '#adaaab',
    outline: '#767576',
    outlineVariant: '#484849',
    surfaceContainerLow: '#131314',
    surfaceContainer: '#1a191b',
    surfaceContainerHigh: '#201f21',
    surfaceContainerHighest: '#262627',
    surfaceContainerLowest: '#000000',
    surfaceBright: '#2c2c2d',
    primaryDim: '#3367ff',
    secondaryDim: '#7e51ff',
    tertiaryDim: '#00d4ec',
    tint: '#94aaff',
    tabIconDefault: '#484849',
    tabIconSelected: '#94aaff',
  },
};

export const Typography = {
  display: {
    fontFamily: 'Manrope_800ExtraBold',
    fontSize: 40,
    letterSpacing: -1,
  },
  headline: {
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    letterSpacing: -0.5,
  },
  title: {
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  body: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
  },
  label: {
    fontFamily: 'Inter_700Bold',
    fontSize: 10,
    textTransform: 'uppercase' as const,
    letterSpacing: 2,
  },
};
